// @ts-check
import { defineConfig } from 'astro/config';

// The org site is the GitHub Pages user site, served from the domain root.
// Quasar's docs live at /quasar/ and are published from accreleus/quasar,
// not from here, so nothing under /quasar/ may be generated by this site.
export default defineConfig({
	site: 'https://accreleus.github.io',
	trailingSlash: 'always',
	markdown: {
		// Same code theme the Quasar docs use.
		shikiConfig: { theme: 'github-dark-default' },
	},
});
